job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Models/CardSearch.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models;
using System.Collections.Generic;

namespace Storm.InterviewTest.Hearthstone.Models
{
    public class CardSearchModel
    {
        public IEnumerable<CardModel> Cards {get; set;}
        public IEnumerable<string> AllPlayerClasses { get; set; }


        public string SelectedPlayerClasses { get; set; }
    }
}

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Models/searchCardsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Storm.InterviewTest.Hearthstone.Models
{
    public class searchCardsModel
    {
    }
}

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Controllers/CardController.cs
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Services;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
	public class CardController : Controller
	{
		public ActionResult Details(string id)
		{
			var searchService = new CardSearchService(MvcApplication.CardCache);

			var model = searchService.FindById(id);

			return View(model);
		}
	}
}

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Controllers/CardsController.cs
using System;
using System.Collections;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Services;
using System.Collections.Generic;
using Storm.InterviewTest.Hearthstone.Models;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
    public class CardsController : Controller
    {

        [HttpGet]
        public ActionResult Index(string q)
        {
            var searchService = new CardSearchService(MvcApplication.CardCache);
            CardSearchModel CardSearch = new CardSearchModel();
            CardSearch.Cards = searchService.Search(q);
            CardSearch.AllPlayerClasses = CardSearch.Cards.Select(m => m.PlayerClassText).Distinct();
            CardSearch.AllPlayerClasses = addBlank(CardSearch.AllPlayerClasses);
            return View(CardSearch);
        }

        [HttpPost]
        public ActionResult Index(CardSearchModel CardSearch, string q, string pl)
		{
			var searchService = new CardSearchService(MvcApplication.CardCache);
            if (!string.IsNullOrEmpty(CardSearch.SelectedPlayerClasses))
                CardSearch.Cards = CardSearch.Cards.Where(c => string.Equals(c.PlayerClass.ToString(), CardSearch.SelectedPlayerClasses, StringComparison.OrdinalIgnoreCase));

            CardSearch.Cards = searchService.Search( q);
            CardSearch.AllPlayerClasses = CardSearch.Cards.Select(m => m.PlayerClassText).Distinct();
            CardSearch.AllPlayerClasses = addBlank(CardSearch.AllPlayerClasses);
            return View(CardSearch);
		}

        private IEnumerable<String>  addBlank( IEnumerable<string> Ienum){
            List<string> blankList = new List<string>{""};
            IEnumerable<string> blankEnum= blankList.AsEnumerable<string>();
            IEnumerable<string> blankAdded = blankEnum.Concat(Ienum);;
            return blankAdded;
        }
	}
}

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Domain;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
	public class HomeController : Controller
	{
		public ActionResult Index()
		{
			return View();
		}
	}
}

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Controllers/MediaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
    public class MediaController : Controller
    {
	    private const string mediaSourceUrl = "http://wow.zamimg.com/images/hearthstone/cards/enus/medium/{0}.png";

        // GET: Media
        public ActionResult Card(string id)
        {
	        var cardFilename = string.Format("{0}.png", id);
	        var localBaseDirectory = Server.MapPath("~/App_Data/media/");
	        Directory.CreateDirectory(localBaseDirectory);
	        var localFile = Path.Combine(localBaseDirectory, cardFilename);
	        if (!System.IO.File.Exists(localFile))
	        {
		        DownloadFromSource(id, localFile);
	        }

			return File(localFile, "image/png");
		}

	    private void DownloadFromSource(string cardId, string localFile) {
		    var client = new WebClient();
			client.DownloadFile(string.Format(mediaSourceUrl, cardId), localFile);
	    }
    }
}

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Controllers/MyDecksController.cs
using System.Web.Mvc;
using Storm.InterviewTest.Hearthstone.Core.Features.Cards.Services;

namespace Storm.InterviewTest.Hearthstone.Controllers
{
	public class MyDecksController : Controller
	{
		public ActionResult Index()
		{
			var searchService = new CardSearchService(MvcApplication.CardCache);
			var heroes = searchService.GetHeroes();
			return View(heroes);
		}
	}
}

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Views/Card/Details.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.CardModel

@{
    ViewBag.Title = "title";
}

@Html.DisplayForModel()

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Views/Cards/Index.cshtml
@model Storm.InterviewTest.Hearthstone.Models.CardSearchModel
@{
    ViewBag.Title = "Home Page";
}

<div class="page-header">
    <h2>Cards (Total: @Model.Cards.Count())</h2>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="row" style="margin-bottom: 10px">
            <div class="col-md-12">
                @using (Html.BeginForm("Index", "Cards",  FormMethod.Post, new { @class = "form-inline", role = "form" }))
            {
                    <div class="container" style="display: inline-block;">
                        <div class="dropdown">
                            <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                                filter by PlayerClass
                                <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" id="pl">
                                @foreach (var PlayerClass in Model.AllPlayerClasses)
                                {
                                    <li><a href="#" style="height: 26px;">@PlayerClass</a></li>

                                }
                            </ul>
                        </div>
                    </div>
                    <input class="form-control" type="search" name="q" id="q" value="" placeholder="search for cards..." />
                    <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                }
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <ul class="list-inline">
                    @foreach (var card in Model.Cards)
                    {
                        <li class="list-group-item">
                            @{ Html.RenderPartial("_card", card); }
                        </li>
                    }
                </ul>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $(".dropdown-menu li a").click(function () {
            $str = $(this).text();
            if ($str == '') {
                $(".btn:first-child").text('filter by PlayerClass');
            }
            else {
                $(".btn:first-child").text('filter by PlayerClass: ' + $str);
            }
            $(".btn:first-child").val($str);
            $("#SelectedPlayerClasses").val($str);
            $('.form-inline').submit();
        });
    });
</script>
@Html.HiddenFor(m => m.SelectedPlayerClasses)
@Html.HiddenFor(m => m.AllPlayerClasses)
@Html.HiddenFor(m => m.Cards)

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Views/Shared/_Card.cshtml
@model Storm.InterviewTest.Hearthstone.Core.Features.Cards.Models.CardModel

<div class="row">
    <div class="col-md-12">
        <a href="@Url.Action("Details", "Card", new { id = Model.Id })"><img class="img-responsive img-thumbnail" src="@Model.ImageUrl" alt="@Model.Name" title="@Model.Name" /></a>        
    </div>
    <div class="col-md-12 text-center">
        <span class="label label-default">@Model.PlayerClassText</span>
    </div>
</div>

job/storm-tech-test-master/Storm.InterviewTest.Hearthstone/Views/Shared/_Layout.cshtml
@using System.Reflection
<!DOCTYPE html>
@{
    var version = string.Empty;
    var versionAttrib = typeof (MvcApplication).Assembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();
    if (versionAttrib != null)
    {
        version = versionAttrib.InformationalVersion;
    }
}

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <img src="~/Content/images/hearthstone.png" height="50" class="pull-left"/>
                @Html.ActionLink("Hearthstone Deck Creator", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Card Browser", "Index", "Cards")</li>
                    <li>@Html.ActionLink("My Decks", "Index", "MyDecks")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p class="pull-left">&copy; Images are copyright of Blizzard Entertainment</p>
            <p class="pull-right">v@(version)</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>